
DROP VIEW IF EXISTS film_complete_info CASCADE;
DROP VIEW IF EXISTS director_statistics CASCADE;
DROP VIEW IF EXISTS actor_filmography CASCADE;
DROP VIEW IF EXISTS film_director_summary CASCADE;
DROP VIEW IF EXISTS film_actor_summary CASCADE;
DROP VIEW IF EXISTS film_rating_avg CASCADE;
DROP VIEW IF EXISTS film_review_stats CASCADE;
DROP VIEW IF EXISTS user_reviews_summary CASCADE;
DROP VIEW IF EXISTS film_directors_sorted CASCADE;
DROP VIEW IF EXISTS film_ratings_full CASCADE;


DROP TABLE IF EXISTS Reviews CASCADE;
DROP TABLE IF EXISTS Film_Actors CASCADE;
DROP TABLE IF EXISTS Films CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Actors CASCADE;
DROP TABLE IF EXISTS Directors CASCADE;
DROP TABLE IF EXISTS Genres CASCADE;

