


REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM app_reader;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM app_reader;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM app_reader;
REVOKE ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA public FROM app_reader;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM app_reader;
REVOKE ALL PRIVILEGES ON DATABASE film_database FROM app_reader;

DROP PROCEDURE IF EXISTS generate_genre_report;
DROP FUNCTION IF EXISTS get_film_verdict;
DROP FUNCTION IF EXISTS log_review_changes;
drop index if exists idx_films_title_year_unique;



DROP VIEW IF EXISTS film_complete_info CASCADE;
DROP VIEW IF EXISTS director_statistics CASCADE;
DROP VIEW IF EXISTS actor_filmography CASCADE;
DROP VIEW IF EXISTS film_director_summary CASCADE;
DROP VIEW IF EXISTS film_actor_summary CASCADE;
DROP VIEW IF EXISTS film_rating_avg CASCADE;
DROP VIEW IF EXISTS film_review_stats CASCADE;
DROP VIEW IF EXISTS user_reviews_summary CASCADE;
DROP VIEW IF EXISTS film_directors_sorted CASCADE;
DROP VIEW IF EXISTS film_ratings_full CASCADE;


DROP TABLE IF EXISTS Genre_Reports CASCADE; 
DROP TABLE IF EXISTS Reviews_Audit CASCADE;
DROP TABLE IF EXISTS Reviews CASCADE;
DROP TABLE IF EXISTS Film_Actors CASCADE;
DROP TABLE IF EXISTS Films CASCADE;         
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Actors CASCADE;
DROP TABLE IF EXISTS Directors CASCADE;
DROP TABLE IF EXISTS Genres CASCADE;

